de:
  title: SWI Multilingual Media Hackahon
  tagline: Wir organisieren einen Hackathon zur Stärkung der sprachlichen Vielfalt in den Redaktionen.
  description: >
    Begleiten Sie uns vom 21. bis 22. Februar 2020 anlässlich des Internationalen Muttersprachentages: ein jährliches Fest der sprachlichen Vielfalt.
  current:
    register: Registrieren
    link: https://swissinfo.typeform.com/to/dNwwCQ
    summary: >
      Wir werden Journalisten, Programmierer, Designer und Experten für Mehrsprachigkeit zusammenbringen, um bessere Lösungen zur Steigerung unserer sprachlichen Vielfalt zu finden. Wir wollen gemeinsam an Lösungen für die Produktion mehrsprachiger Medieninhalte wie Text, Video und Grafik arbeiten.
    details: Weiter lesen

fr:
  title: SWI Multilingual Media Hackahon
  tagline: Nous organisons un hackathon sur l'autonomisation de la diversité linguistique dans les salles de rédaction.
  description: >
    Joignez-vous à nous les 21 et 22 février 2020 pour la Journée internationale de la langue maternelle: une célébration annuelle de la diversité linguistique.
  current:
    register: Registration
    link: https://swissinfo.typeform.com/to/dNwwCQ
    summary: >
      Nous réunirons des journalistes, des codeurs, des concepteurs et des experts en multilinguisme afin de trouver de meilleures solutions pour élever notre diversité linguistique. Nous voulons travailler en collaboration sur des solutions pour la production de contenu multimédia multilingue, y compris du texte, de la vidéo et des graphiques.
    details: Savoir plus

en:
  title: SWI Multilingual Media Hackahon
  tagline: We are organizing a hackathon on empowering linguistic diversity in newsrooms.
  description: >
    Join us on Feb. 21–22, 2020 to mark International Mother Language Day: a yearly celebration of linguistic diversity.
  current:
    register: Register
    link: https://swissinfo.typeform.com/to/dNwwCQ
    summary: >
      We will bring together journalists, coders, designers, and experts in multilingualism to find better solutions to elevate our linguistic diversity. We want to collaboratively work on solutions for multilingual media content productions, including text, video, and graphics.
    details: Detailed info

# Site links
title: swihack
url: "https://swihack.ch"
email: info@schoolofdata.ch
forum: "https://forum.opendata.ch/t/21-22-02-swi-multilingual-media/598/3"
twitter: schoolofdata_ch
calendar: https://forum.schoolofdata.ch/t/upcoming-events/40
facebook: schoolofdata
github: schoolofdata-ch
grecaptcha:
  key: 6Lco8A8UAAAAAH68UXg94Ib9ptw6fRGxnZtSb0oQ

# Build settings
baseurl: "" # the subpath, e.g. /blog
markdown: kramdown
sass:
  sass_dir: sass
